### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by bjorns** [hugorut/motivation#6]
Not sure if I did something wrong but I got this:

```
$ motivator -m "C S Lewis"
/usr/local/lib/ruby/gems/2.3.0/gems/motivator-1.0.4/lib/motivator.rb:35:in `get_quote': undefined method `length' for nil:NilClass (NoMethodError)
    from /usr/local/lib/ruby/gems/2.3.0/gems/motivator-1.0.4/lib/motivator.rb:15:in `motivate'
    from /usr/local/lib/ruby/gems/2.3.0/gems/motivator-1.0.4/bin/motivator:21:in `<top (required)>'
    from /usr/local/bin/motivator:23:in `load'
    from /usr/local/bin/motivator:23:in `<main>'
```

**Comment by hugorut** [comment]
hi, yes currently the gem only supports underscored names so the command would be 

`motivator -m c_s_lewis`

hopefully get some string matching in there soon
